# Generated by Django 3.1 on 2020-08-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='op',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=100),
        ),
    ]
